services:
  test:
    image: mpi-node
    networks:
      - mpinet
    volumes:
      - .:${PWD}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-4}

networks:
  mpinet:
    name: mpinet
    driver: bridge
