name: run-tests-ci

on: push

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Preparing container
        run: |
          docker build -t mpiwcpp17-test test
          docker container create -i -t --name test-runner mpiwcpp17-test
          docker start test-runner
          docker cp . test-runner:/home/mpiwcpp17
      - name: Building and running test cases
        run: |
          docker exec test-runner make runtest np=4
          docker cp test-runner:/home/mpiwcpp17/coverage.info .
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.info
