name: run-tests-ci

on: [push, pull_request]

jobs:
  test-runner:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        mpi: [mpich, openmpi]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jwlawson/actions-setup-cmake@v1

      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Configure project with CMake
        run: cmake -S . -B build -DBUILD_TESTING=ON -G Ninja

      - name: Build project
        run: cmake --build build

      - name: Run tests locally
        env:
          USE_MPI_EMULATOR: local
          USE_MPI_PROCESSES: 4
        run: ctest --test-dir build --output-on-failure

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true
