name: run-tests-docker

on: [push, pull_request]

jobs:
  test-docker-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jwlawson/actions-setup-cmake@v1

      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: openmpi

      - name: Configure project with CMake
        run: cmake -S . -B build -DBUILD_TESTING=ON -G Ninja

      - name: Build project
        run: cmake --build build

      - name: Prepare Docker image
        run: docker build -t mpinode support

      - name: Initialize MPI Docker cluster
        run: docker compose --file support/docker-compose.yml --project-directory . up -d

      - name: Run tests on MPI Docker cluster
        env:
          USE_MPI_EMULATOR: docker
          USE_MPI_PROCESSES: 4
        run: ctest --test-dir build --output-on-failure
