name: run-tests-ci

on: [push, pull_request]

jobs:
  test-runner:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        mpi: [mpich, openmpi]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build

      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Configure project with CMake
        run: |
          cmake -S . -B build   \
            -DBUILD_TESTING=ON  \
            -G Ninja

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
