name: run-tests-ci

on: [push, pull_request]

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Preparing container
        run: |
          docker build -t mpiwcpp17-test test
          docker container create -i -t --name test-runner mpiwcpp17-test
          docker start test-runner

      - name: Building and running test cases
        run: |
          make distribute
          docker cp . test-runner:/home/mpiwcpp17
          docker exec test-runner make run-tests -j NP=$(nproc)
